### ISSUE TITLE
SLV check_value with Z

### ISSUE THREAD

**Issue by aksoandrefi** [UVVM/UVVM#102]
Hi 
When I run check_value on two SLVs with Z (high impedance) I get the following error:
check_value() => Failed. slv  Was x"ZZ" (b"ZZZZZZZZ"). Expected x"ZZ" (b"ZZZZZZZZ").

I see in the code that it is possible to set the match_strictness to a value called "MATCH_STD_INCL_Z", but this value is not documented in the QuickRef document. 

Best regards
Andre

**Comment by UVVM** [comment]
Hi, 
We will add this to Util QR in the next release.

Best regards,
Marius

**Comment by UVVM** [comment]
This issue has been fixed in the v2 2020.04.20 release.
