### ISSUE TITLE
Bug in Clock Generator VVC

### ISSUE THREAD

**Issue by fergzie** [UVVM/UVVM#107]
There is a minor bug in the Clock Generator VVC on line 52.

`assert (GC_CLOCK_NAME'length <= 20) report "Clock name is too long (max 30 characters)" severity ERROR;`

The assertion checks for length of max 20 characters, but the text states 30.

**Comment by UVVM** [comment]
Hi,
Thank you, this will be fixed in the next release.

Best regards,
Marius
