### ISSUE TITLE
axilite_bfm_pkg has blank if-else branch

### ISSUE THREAD

**Issue by spikev** [UVVM/UVVM#109]
line 601 is blank (the last if-else-endif in axifull_read)

**Comment by UVVM** [comment]
Hi,

Thank you for the observation. The else should have a comment like this:
    else
    -- Log will be handled by calling procedure (e.g. axilite_check)
    end if;
We will fix it in our next release.

Best regards,
Erick

**Comment by UVVM** [comment]
The new UVVM version 2020.05.19 has been released.
