### ISSUE TITLE
vip_axistream : ready low cycles not reset

### ISSUE THREAD

**Issue by Obliged** [UVVM/UVVM#122]
### Effect:
When using the configuration config.ready_low_at_word_num = C_MULTIPLE_RANDOM we don't get multiple ready lows.

### Cause
v_ready_low_cycle_count is not set back to zero within the loop. The effect is that the _sum_ of ready low cycles is determined by ready_low_duration.

### Fix
` v_ready_low_cycle_count := 0;` in axistream_bfm_pkg line 1356.

**Comment by UVVM** [comment]
Hi,

Thank you for reporting the bug, we will fix it in our next release.
By the way, there is a similar issue on the transmit side with the config.valid_low_at_word_num = C_MULTIPLE_RANDOM.

Best regards,
Erick

**Comment by mariuselv** [comment]
Fixed in v2_v2020.12.08
