### ISSUE TITLE
shared_activity_watchdog

### ISSUE THREAD

**Issue by AndersAlme** [UVVM/UVVM#123]
Have some VVC I created in the spring that calls the variable shared_activity_watchdog from the file ti_vvc_framework_support_pkg. In the newest releases this variable is gone. What should I do to modify my old VVCs to incorporate them in the new version?

**Comment by mariuselv** [comment]
Hi, 
The VVCs now calls a update_vvc_activity_register() method in the vvc_methods_pkg from its cmd_executor process:

`      -- update vvc activity
      update_vvc_activity_register(global_trigger_vvc_activity_register, vvc_status, INACTIVE, entry_num_in_vvc_activity_register, last_cmd_idx_executed, command_queue.is_empty(VOID), C_SCOPE);

      -- 1. Set defaults, fetch command and log
      -------------------------------------------------------------------------
      work.td_vvc_entity_support_pkg.fetch_command_and_prepare_executor(v_cmd, command_queue, vvc_config, vvc_status, queue_is_increasing, executor_is_busy, C_VVC_LABELS);

      -- update vvc activity
      update_vvc_activity_register(global_trigger_vvc_activity_register, vvc_status, ACTIVE, entry_num_in_vvc_activity_register, last_cmd_idx_executed, command_queue.is_empty(VOID), C_SCOPE);
`
