### ISSUE TITLE
bitvis_vip_spec_cov not in component_list.txt

### ISSUE THREAD

**Issue by TheQuill** [UVVM/UVVM#125]
When using the compile_all.do script which uses the component_list.txt i would expect all folder in uvvm to build. However, the spec coverage is not in this list and is not build when using the compile_all script.

Unless this is on purpose, i propose updating the list.

On second look, xConstrRandFuncCov is also not in this list.

**Comment by mariuselv** [comment]
Hi,
The Bitvis VIP Spec Cov should be included in the compile_all script; I will add this to the next release. The xConstrRandFuncCov will not be added.

Br,
Marius

**Comment by mariuselv** [comment]
Fixed in v2_v2020.12.08
