### ISSUE TITLE
Support terminating commands in SPI VVC executor

### ISSUE THREAD

**Issue by am9417** [UVVM/UVVM#190]
There should be possibility to terminate (or timeout) at least the slave-side commands in bitvis_vip_spi.

**Comment by am9417** [comment]
#191

**Comment by UVVM** [comment]
Great suggestion.
Could you please change the procedure parameter from terminate_loop to terminate_access, as your pull request allows terminating throughout the access and not just at the start.

**Comment by am9417** [comment]
> Great suggestion. Could you please change the procedure parameter from terminate_loop to terminate_access, as your pull request allows terminating throughout the access and not just at the start.

Good to hear. Yes, I renamed it to `terminate_access`, that's better.

**Comment by UVVM** [comment]
Entered as pull request. Thus closed here.
https://github.com/UVVM/UVVM/pull/191
