### ISSUE TITLE
AXI-Stream VVC deprecated log message

### ISSUE THREAD

**Issue by runeben** [UVVM/UVVM#193]
The deprecated procedure axistream_transmit_bytes is called regardless of which axistream_transmit procedure the user has called. So, even if you call the axistream_transmit procedure with data_array as t_slv_array, the log will contain the following message "Sub-program axistream_transmit is outdated and has been replaced by another sub-program. data_array as t_byte_array has been deprecated. Use data_array as t_slv_array."

**Comment by UVVM** [comment]
Fixed in release v2023.03.10
