### ISSUE TITLE
[SUGGESTION]: Tour of UVVM and UVVM examples using CodeTour

### ISSUE THREAD

**Issue by sibeov** [UVVM/UVVM#207]
# Intro
Have no association with the plugin at all, but its quite a nifty VSCode plugin for sure.

## CodeTour
[CodeTour](https://marketplace.visualstudio.com/items?itemName=vsls-contrib.codetour) allows you to have a step-by-step guided tour through a codebase in `Visual Studio Code`. Uses `.json` files and has a simple GUI in `VScode` to create the guides.

## Suggestion
Use this tool to add guided tours of the UVVM repo. Both the IPs, how UVVM works in general an example etc. Greate way to link knowledge to the practicalities. Nice to use for reviews as well.

## Note
As always, thanks for making UVVM an amazing tool.

Kind Regards
sibeov

**Comment by UVVM** [comment]
Hi! Although it might add value for some users, this would require us to maintain the guide on new releases and changes to the code. Another issue is that, as far as we can see, there is no way of showing other windows such as a simulator. Is this possible? We will keep this tool in mind in the future. thank you for the input!
