### ISSUE TITLE
Why UVVM tagged with v2_v2024.03.08 differs from the one at IEEE

### ISSUE THREAD

**Issue by mdykierek** [UVVM/UVVM#236]
This: https://github.com/UVVM/UVVM/releases/tag/v2_v2024.03.08
differs from: https://opensource.ieee.org/uvvm/uvvm/-/tags/v2_v2024.03.08

Which one is correct?
Will tagging be corrected where appropriate?

**Comment by UVVM** [comment]
Thanks for reporting.
Both tags have been corrected.

Br,
UVVM
