### ISSUE TITLE
Which version of UVVM is  now correct?

### ISSUE THREAD

**Issue by mdykierek** [UVVM/UVVM#245]
[v2024.07.04](https://github.com/UVVM/UVVM/releases/tag/v2024.07.04)
[v2024.07.03b](https://github.com/UVVM/UVVM/releases/tag/v2024.07.03b)
or
[v2024.07.03b](https://opensource.ieee.org/uvvm/uvvm/-/tags/v2024.07.03b)

**Comment by UVVM** [comment]
Hi,
The v2024.07.03b version should be correct.

**Comment by mdykierek** [comment]
v2024.07.03b on github and IEEE differ a bit (a couple of files missing and wrong letter case in LICENSE.TXT filenames).

**Comment by UVVM** [comment]
Oo, thanks for reporting. 
We will correct the tags etc after the summer vacation. 

Br

**Comment by UVVM** [comment]
A new version of UVVM has been released, https://github.com/UVVM/UVVM/releases/tag/v2_2024.08.16
