### ISSUE TITLE
(docu) axistream_receive / Bitvis VIP AXI4-Stream

### ISSUE THREAD

**Issue by 1pilo** [UVVM/UVVM#262]
Documentation of https://uvvm.github.io/vip_axistream.html#axistream-receive-vvc
Has a typing error in the example of axistream_receive.
![image](https://github.com/user-attachments/assets/68325f65-1d47-4d19-8c8d-9cd71370fb8d)

**Comment by 1pilo** [comment]
#263

**Comment by 1pilo** [comment]
#263

**Comment by UVVM** [comment]
Thanks. Will check pull request.
