### ISSUE TITLE
endianness of axistream

### ISSUE THREAD

**Issue by eschmidscs** [UVVM/UVVM#40]
Hej

The current axistream VVC and BFM convert t_slv_array payloads with FIRST_BYTE_LEFT to t_byte_array. This corresponds to big endian.

I think this should be configurable. The axistream spec does not contain a remark about endianness at all, the full axi spec leaves that open on purpose.

Best regards,
emanuel

**Comment by eschmidscs** [comment]
... ps: I'm not providing a solution as my axistream is hacked into pieces due to the two issues caused by questa-bugs. If I find time I'll try to clean that up and provide patch.

**Comment by UVVM** [comment]
The configurable byte endianness feature was released in v2018.04.09
