### ISSUE TITLE
Broken README in the OSVVM directory

### ISSUE THREAD

**Issue by Paebbels** [UVVM/UVVM#56]
This is a followup on #53.

With PR #55, several issues where introduced in this [README.md](https://github.com/UVVM/UVVM/blob/master/xConstrRandFuncCov/README.md):
- broken headline + typo in the headline
- missing forced linebreak before `**License**`
- broken link to the PAL 2.0 license

See PR #55 for further details.

**Comment by UVVM** [comment]
Thanks Patrick.
Should be fixed now.

**Comment by Paebbels** [comment]
Thanks for fixing.
