### ISSUE TITLE
Use Avalon_mm as a slave ?

### ISSUE THREAD

**Issue by sinitame** [UVVM/UVVM#59]
Hi,
I wanted to use Avalon MM bfm as a slave in my projet but I just figured out that it seems to be only available as a master. Is there any way to use it as a slave ?

To be more precise, I have a component which needs to perform reads and writes in my FPGA DDR through the DSP which is using Avalon protocol to communicate. I want to test my component with an interface that could act as a Avalon BFM slave. If it's not possible with UVVM VVCs  is there any other possibility to achieve this easily ?

Best regards

**Comment by UVVM** [comment]
Hi,

Unfortunately we only have a master version of Avalon-MM available as a VVC, and we don't have a slave version on our roadmap at the moment.
You can use the VVC generator to get started if you decide to make your own Avalon-MM slave VVC.
It is located under uvvm_vvc_framework/script/
We also have a repo for 3rd party VIPs if you would like to share it with others: https://github.com/UVVM/UVVM_3rd_party_VIP

Best regards
Arild
