### ISSUE TITLE
Common compile_src.do script bug

### ISSUE THREAD

**Issue by fergzie** [UVVM/UVVM#60]
All compile_src.do have a common bug in the following code

} elseif {$argc >= 2} {
    echo "\nUser specified source and target directory"
    quietly set target_path "$2"
    quietly set default_target 0

There is missing : quietly set source_path "$1"

So the code should be:

} elseif {$argc >= 2} {
    echo "\nUser specified source and target directory"
    quietly set source_path "$1"
    quietly set target_path "$2"
    quietly set default_target 0

**Comment by UVVM** [comment]
Hi and thank you for your feedback!
A fix will be pushed with a new release soon!

Best regards,
Marius
