### ISSUE TITLE
Extra spaces at the end of some lines.

### ISSUE THREAD

**Issue by m-kru** [UVVM/UVVM#71]
I have realized that UVVM produces a lot of extra spaces at the end of lines. Are they really necessary?
2 examples:
![uvvm_spaces](https://user-images.githubusercontent.com/26227737/51930017-eb1ebd80-23f9-11e9-9695-1dad22bd7500.png)

![uvvm_spaces_2](https://user-images.githubusercontent.com/26227737/51930023-ef4adb00-23f9-11e9-8a9d-42b35d2e2326.png)

**Comment by UVVM** [comment]
Hi,

Some of the spaces are meant for easier alignment, for example in lines 16 and 17 to start the lines at the same offset, however the spaces at the end of the lines seem a bit unnecessary.

We will remove the ones in the reports, but the ones in single print outs require more work. Is this a big problem for you?

Best regards,
Erick

**Comment by m-kru** [comment]
@UVVM It is not a problem for me at all. I just don't like thins that are superfluous :).

**Comment by UVVM** [comment]
Hi,

I agree and we'll try to avoid this in the future. For now the extra spaces in the reports have been removed and this will be in our next release.

Best regards,
Erick

**Comment by UVVM** [comment]
Hi,
This issue has been fixed in the lastest release.

Best regards,
Marius
