### ISSUE TITLE
Status of wishbone BFM?

### ISSUE THREAD

**Issue by m-kru** [UVVM/UVVM#77]
What is the status of wishbone BFM? 
There was an issue a few months ago where you mentioned that  someone was already working on that.

**Comment by m-kru** [comment]
@UVVM ping

**Comment by UVVM** [comment]
Hi,
I will need to check with the developer working with this BFM. He is currently on vacation, but I will get back to you as soon as I've heard from him.

Br,
Marius

**Comment by UVVM** [comment]
A beta version is published in the Community VIPs repository.
