### ISSUE TITLE
Can configuring VVCs and their BFMs be a procedure call?

### ISSUE THREAD

**Issue by fergzie** [UVVM/UVVM#81]
When configuring a VVC and BFM with **shared_<Insert VVC name>_vvc_config** there is no check if the VVC actually exists. 

E.g. I accidentally called **shared_axistream_vvc_config** with an index which there was no VVC present, but the number was in the range 0 to C_MAX_VVC_INSTANCE_NUM-1, so nothing happened. This took me some time to find and correct.

Can this be changed, so that it has a built-in mechanism to check whether or not the VVC exists?

**Comment by UVVM** [comment]
Hi,
Yes, but it will require a bit work to implement this feature. We recommend that our users use constants as VVC indexes.
A potential solution would be to add a procedure to each VVC to set the VVC configuration record and check that it exists. 
We will consider implementing this in a future release.

Br.
Marius
