### ISSUE TITLE
Outdated documentation for uart_bfm_QuickRef

### ISSUE THREAD

**Issue by andmeyee** [UVVM/UVVM#92]
Documentation for uart_transmit() found in _UVVM/bitvis_vip_uart/doc/uart_bfm_QuickRef.pdf_ is outdated. `clk` signal is no more a parameter of the procedure and results in compilation error. See _UVVM/bitvis_vip_uart/src/uart_bfm_pkg.vhd_ for correct implementation.

**Comment by UVVM** [comment]
Thank you for the feedback! An updated QR is coming soon.

Best regards,
Marius

**Comment by UVVM** [comment]
Documentation has been updated in v2019.12.04 release.
