### ISSUE TITLE
Missing feature to deallocate UVVM FIFO

### ISSUE THREAD

**Issue by fergzie** [UVVM/UVVM#94]
I'd like to request a feature that I'm missing. There is no way to deallocate a UVVM FIFO, but the data queue package, which UVVM FIFO is built upon, does support deallocation of buffer.

**Comment by UVVM** [comment]
Hi,

Yes there is a procedure deallocate_buffer() which resets all the pointers in the buffer thus deallocating ALL the queues. Is this the feature you would like for the UVVM FIFO? Because deallocating a single FIFO requires a more complex procedure.

Best regards,
Erick

**Comment by fergzie** [comment]
Hi Erick,

Yes I'd like that feature for the UVVM FIFO.

Br,
David

**Comment by UVVM** [comment]
Alright, then we'll make sure to add that feature in our next release.

**Comment by fergzie** [comment]
Great. Thank you :+1:

**Comment by UVVM** [comment]
New release is out.
